variables:
  GIT_DEPTH: 1

build:
  stage: build
  image: gradle:6.1-jdk
  script:
    - cp _ci/build.gradle .
    - gradle build
  artifacts:
    paths:
      - gen/

test:
  stage: test
  image: hseeberger/scala-sbt:8u242_1.3.7_2.13.1
  script:
    - sbt test
